version: "3.8"
services:
  database_dev:
    hostname: aws-archiver_database_dev
    image: postgres:14.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=superadmin
      - POSTGRES_PASSWORD=javaMyPassion4Ever
      - POSTGRES_DB=archiver_db
    volumes:
      - '/archiver_db-db_dev-data'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=superadmin --dbname=archiver_db"]
      interval: 10s
      timeout: 5s
      retries: 5
  back-end_dev:
    hostname: aws-archiver_dev
    image: develop:latest
    ports:
      - "8081:8081"
    depends_on:
      - database_dev
    environment:
      SPRING_ACTIVE_PROFILE: development
      JDBC_DATABASE_URL: "jdbc:postgresql://database_dev:5432/archiver_db"
    volumes:
      - '${HOME}:/root'
