server:
  port: ${DEV_PORT:8080}
  servlet:
    contextPath: /api
  error:
    include-message: always

spring:
  application:
    name: aws-archiver
  jpa:
    generate-ddl: false
    hibernate.ddl-auto: validate #update #create
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        schema_update.unique_constraint_strategy: RECREATE_QUIETLY
        jdbc:
          lob.non_contextual_creation: true
          time_zone: UTC
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/archiver_db}
    username: ${JDBC_DATABASE_USERNAME:superadmin}
    password: ${JDBC_DATABASE_PASSWORD:javaMyPassion4Ever}
    hikari.maximum-pool-size: ${hikari-maximum-pool-size:5}
  liquibase:
    enabled: true
    changelog: /db/changelog/changelog.groovy